version: '3.8'

services:
  app:
    build:
      context: .
      target: base
    container_name: betterrepo2file
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app/app
      - ./repo2file:/app/repo2file
      - ./uploads:/app/uploads
      - ./temp:/app/temp
    environment:
      - FLASK_APP=app/app.py
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  test:
    build:
      context: .
      target: test-runner
    container_name: betterrepo2file-tests
    volumes:
      - ./test_results:/app/test_results
      - ./tests:/app/tests
      - ./app:/app/app
      - ./repo2file:/app/repo2file
    environment:
      - PYTHONPATH=/app
    profiles:
      - test

  test-docker:
    build:
      context: .
      dockerfile: Dockerfile
      target: test-runner
    container_name: betterrepo2file-test-docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test_results:/app/test_results
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
    profiles:
      - test-docker